name: Code Quality
on:
    push:
    pull_request:
        types: [opened, reopened]
jobs:
    code_quality:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout ğŸ›
              uses: actions/checkout@v4

            - name: Install node ğŸ—
              uses: actions/setup-node@v3
              with:
                node-version: 20.16.0
                check-latest: true

            - name: Install Bun ğŸ
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: 1.1.24

            - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
              run: bun install --frozen-lockfile

            - name: Run linter ğŸ‘€
              run: bunx nx run-many --target=lint --all

            - name: Run tests ğŸ§ª
              run: bunx nx run-many --target=test --all

            - name: Run build ğŸ—
              run: bunx nx run-many --target=build --all

